#!/bin/bash
python cal_ensemble.py $1
N=`grep 'N_config' config.py | awk '{print $NF}'`
cd run_dft$1
cp -r ../pseudo_espresso ./
cp ../sub_dft ./
N1=$((N/32))
for i in `seq 1 ${N1}`
do
sbatch sub_dft $i
done