#!/bin/bash
if [ -d 'run_dft$1' ]; then 
	echo "run_dft$1 exists, please delete it first"
    exit  
fi 
python generate_init_input.py
python cal_ensemble.py $1
N=`grep 'N_config' config.py | awk '{print $NF}'`
n1=`grep 'nrun_per_node' config.py | awk '{print $NF}'`
n2=`grep 'n_node_per_job' config.py | awk '{print $NF}'`
if [  -d "run_dft$1" ]; then
	cd run_dft$1
	cp -r ../pseudo_espresso ./
	cp ../sub_dft ./
	N1=`python -c "from math import ceil;print(ceil($N/$n2/$n1))"`
	for i in `seq 1 ${N1}`
	do
		mkdir -p d$i
		cd d$i
		# cp ../*pwi ./
		cp ../sub_dft ./
		sbatch sub_dft $i
		cd ..
	done	
fi