#!/bin/bash
# Slurm job options (job-name, compute nodes, job time)
#SBATCH --nodes=4
#SBATCH --account=e89-ic_m
#SBATCH --partition=standard
#SBATCH --qos=standard
#SBATCH --time=01:0:0

# Set the number of threads to 1
#   This prevents any threaded system libraries from automatically
#   using threading.
export OMP_NUM_THREADS=1

module load quantum_espresso
I=$1
echo "Starting 32 jobs across 4 nodes each using 16 CPUs"

# Loop over 32 subjobs each using 16 CPUs, running in background

for i in $(seq 1+(I-1)*32 I*32)
do
   echo "Launching job number $i"

   # Launch subjob overriding job settings as required and in the
   # background. Make sure to change the `--mem=` flag to the amount
   # of memory required. A sensible amount is 1.5 GiB per task as
   # this leaves some overhead for the OS etc.

   srun --unbuffered --nodes=1 --ntasks=16 --tasks-per-node=16 \
        --cpus-per-task=1 --distribution=block:block --hint=nomultithread \
        --mem=10G --exact \
        pw.x < espresso_run_${i}.pwi > espresso_run_${i}.pwo &

done
# Wait for all subjobs to finish
echo "Waiting for all jobs to finish ..."

wait

echo "... all jobs finished"