#!/bin/bash
# 
# Parallel script produced by bolt
#        Resource: ARCHER2 (HPE Cray EX (128-core per node))
#    Batch system: Slurm
#
# bolt is written by EPCC (http://www.epcc.ed.ac.uk)
#
#SBATCH --nodes=4
#SBATCH --tasks-per-node=128
#SBATCH --cpus-per-task=1
#SBATCH --job-name=s1
#SBATCH --account=e89-ic_m
#SBATCH --partition=standard
#SBATCH --qos=taskfarm
#SBATCH --time=01:0:0
module load quantum_espresso
I=$1
for i in $(seq 1 32)
do
index=$((I*32+1-i))
srun --nodes=1 --ntasks=16 --ntasks-per-node=16 --mem=10240M --distribution=block:block --hint=nomultithread pw.x < espresso_run_${index}.pwi > espresso_run_${index}.pwo
#echo ${index}
done